# Generated by Django 4.2 on 2023-04-15 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0003_alter_evento_partcipantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='partcipantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='evento_participante', to=settings.AUTH_USER_MODEL),
        ),
    ]
