# Generated by Django 4.2 on 2023-04-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_partcipantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='partcipantes',
            new_name='participantes',
        ),
    ]
